module.exports = {
    userId:             localStorage.getItem('userId'),
    userRole:           localStorage.getItem('userRole'),
    boolIsLogged:       localStorage.getItem('boolIsLogged'),
    firstName:          localStorage.getItem('firstName'),
    midName:            localStorage.getItem('midName'),
    lastName:           localStorage.getItem('lastName'),
    email:              localStorage.getItem('email'),
    primaryPhysician:   localStorage.getItem('primaryPhysician'),
    approvedDoctors:    localStorage.getItem('approvedDoctors'),
    isAdmin:            localStorage.getItem('isAdmin'),
    patientCount:       localStorage.getItem('patientCount'),
    doctorCount:        localStorage.getItem('doctorCount'),
    apptCount:          localStorage.getItem('apptCount'),
    testCount:          localStorage.getItem('testCount'),
};