# Generated by Django 3.2.7 on 2021-09-25 20:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.TextField()),
                ('lastname', models.TextField()),
                ('DoB', models.DateField()),
                ('address', models.TextField()),
                ('primarydoctor', models.TextField()),
                ('primarylocation', models.TextField()),
                ('documents', models.FileField(storage=django.core.files.storage.FileSystemStorage('../storage/documents'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.TextField()),
                ('details', models.TextField()),
                ('documents', models.FileField(storage=django.core.files.storage.FileSystemStorage('../storage/documents'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField()),
                ('documents', models.FileField(storage=django.core.files.storage.FileSystemStorage('../storage/documents'), upload_to='')),
            ],
        ),
    ]
