# Generated by Django 3.2.7 on 2021-10-21 22:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentUID', models.UUIDField()),
                ('paitientProfileUID', models.UUIDField()),
                ('doctorProfileUID', models.UUIDField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('locationUID', models.UUIDField()),
                ('doctors_notes', models.TextField()),
                ('reports', models.FileField(storage=django.core.files.storage.FileSystemStorage('../storage/documents'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='doctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userGUID', models.UUIDField()),
                ('doctorProfileUID', models.UUIDField()),
                ('first_name', models.TextField()),
                ('mid_name', models.TextField()),
                ('last_name', models.TextField()),
                ('DoB', models.DateField()),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip', models.TextField()),
                ('idnum', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone1', models.TextField()),
                ('phone2', models.TextField()),
                ('phone3', models.TextField()),
                ('documents', models.FileField(storage=django.core.files.storage.FileSystemStorage('../storage/documents'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inboxUID', models.UUIDField()),
                ('userGUID', models.UUIDField()),
                ('toDemoUID', models.UUIDField()),
                ('subject', models.CharField(help_text='subject', max_length=200)),
                ('body', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('documents', models.FileField(storage=django.core.files.storage.FileSystemStorage('../storage/documents'), upload_to='')),
                ('isRead', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insuranceUID', models.UUIDField()),
                ('name', models.CharField(help_text='address', max_length=200)),
                ('accountid', models.CharField(help_text='address', max_length=200)),
                ('insuranceType', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationUID', models.UUIDField()),
                ('name', models.TextField(help_text='name place', max_length=200)),
                ('address1', models.TextField(help_text='address', max_length=200)),
                ('address2', models.TextField(help_text='address', max_length=200)),
                ('city', models.CharField(help_text='address', max_length=200)),
                ('State', models.CharField(help_text='address', max_length=200)),
                ('zip', models.CharField(help_text='address', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificationUID', models.UUIDField()),
                ('appointmentUID', models.UUIDField()),
                ('reportUID', models.UUIDField()),
                ('inboxUID', models.UUIDField()),
                ('messages', models.CharField(help_text='reminder', max_length=200)),
                ('link', models.URLField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doEmail', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='paitientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userGUID', models.UUIDField()),
                ('paitientProfileUID', models.UUIDField()),
                ('first_name', models.TextField()),
                ('mid_name', models.TextField()),
                ('last_name', models.TextField()),
                ('DoB', models.DateField()),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('zip', models.TextField()),
                ('idnum', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone1', models.TextField()),
                ('phone2', models.TextField()),
                ('phone3', models.TextField()),
                ('Insurance01UID', models.TextField()),
                ('Insurance02UID', models.TextField()),
                ('Insurance03UID', models.TextField()),
                ('documents', models.FileField(storage=django.core.files.storage.FileSystemStorage('../storage/documents'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportUID', models.UUIDField()),
                ('appointmentUID', models.UUIDField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('details', models.TextField()),
                ('documents', models.FileField(storage=django.core.files.storage.FileSystemStorage('../storage/documents'), upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='customUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
