# Generated by Django 3.2.7 on 2021-09-25 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telemedicine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='primarydoctor',
            new_name='primary_doctor',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='primarylocation',
            new_name='primary_location',
        ),
        migrations.AddField(
            model_name='appointments',
            name='patient_name',
            field=models.CharField(default='', help_text='Patients full name', max_length=200),
            preserve_default=False,
        ),
    ]
